---
version: '2.4'
services:
    elasticsearch:
        image: ${ELASTICSEARCH_IMAGE}
        restart: always
        environment:
            - 'node.name=INEP'
            - 'discovery.type=single-node'
            - 'bootstrap.memory_lock=true'
            - 'ES_JAVA_OPTS=-Xms256m -Xmx256m'
        ports:
            - 9200:9200
            - 9300:9300
        volumes:
            - type: bind
              source: ./elasticsearch
              target: /usr/share/elasticsearch/data
        networks:
            - efk
        logging:
            driver: fluentd
            options:
                fluentd-address: localhost:24224
                fluentd-async-connect: 'true'
                fluentd-retry-wait: '1s'
                fluentd-max-retries: '30'
                tag: ${LOG_OPT_TAG_PREFIX}.efk.elasticsearch

    kibana:
        image: ${KIBANA_IMAGE}
        restart: always
        ports:
            - 5601:5601
            - 443:5601
        networks:
            - efk
        depends_on:
            - elasticsearch
        logging:
            driver: fluentd
            options:
                fluentd-address: localhost:24224
                fluentd-async-connect: 'true'
                fluentd-retry-wait: '1s'
                fluentd-max-retries: '30'
                tag: ${LOG_OPT_TAG_PREFIX}.efk.kibana

    fluentd:
        image: ${FLUENTD_IMAGE}
        ports:
            - 127.0.0.1:24224:24224
            - 8080:24224
#            - 24224:24224/udp
        volumes:
            - ./fluentd/etc:/fluentd/etc
        networks:
            - efk
        logging:
            driver: "json-file"
            options:
                max-size: "1G"
                max-file: "2"

    apm:
        image: ${APMSERVER_IMAGE}
        ports:
            - 8200:8200
        networks:
            - efk
        depends_on:
            - elasticsearch
            - kibana
        logging:
            driver: fluentd
            options:
                fluentd-address: localhost:24224
                fluentd-async-connect: 'true'
                fluentd-retry-wait: '1s'
                fluentd-max-retries: '30'
                tag: ${LOG_OPT_TAG_PREFIX}.efk.apm
        volumes:
            - type: bind
              source: ./apm-server/conf/apm-server.yml
              target: /usr/share/apm-server/apm-server.yml

    nginx:
        image: ${NGINX_IMAGE}
        restart: always
        ports:
            - 80:80
        volumes:
            - type: bind
              source: ./nginx/nginx.conf
              target: /etc/nginx/nginx.conf
              read_only: true
            - type: bind
              source: ./nginx/conf.d
              target: /etc/nginx/conf.d
              read_only: true
        networks:
            - efk
        depends_on:
            - kibana
        logging:
            driver: fluentd
            options:
                fluentd-address: localhost:24224
                fluentd-async-connect: 'true'
                fluentd-retry-wait: '1s'
                fluentd-max-retries: '30'
                tag: ${LOG_OPT_TAG_PREFIX}.efk.nginx
networks:
    efk:
        driver: bridge
